[2023-03-29 15:55:38,864] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:23:15.177924+00:00 [queued]>
[2023-03-29 15:55:38,883] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:23:15.177924+00:00 [queued]>
[2023-03-29 15:55:38,883] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 15:55:38,883] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2023-03-29 15:55:38,883] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 15:55:38,908] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): merge_task> on 2023-03-29 15:23:15.177924+00:00
[2023-03-29 15:55:38,914] {standard_task_runner.py:52} INFO - Started process 165 to run task
[2023-03-29 15:55:38,916] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_merge_dag', 'merge_task', 'manual__2023-03-29T15:23:15.177924+00:00', '--job-id', '605', '--raw', '--subdir', 'DAGS_FOLDER/data_merge.py', '--cfg-path', '/tmp/tmpd6l2x6jt', '--error-file', '/tmp/tmpbik1cqxe']
[2023-03-29 15:55:38,917] {standard_task_runner.py:80} INFO - Job 605: Subtask merge_task
[2023-03-29 15:55:38,974] {task_command.py:369} INFO - Running <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:23:15.177924+00:00 [running]> on host 4513f77b4fd8
[2023-03-29 15:55:39,062] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kartaca
AIRFLOW_CTX_DAG_ID=data_merge_dag
AIRFLOW_CTX_TASK_ID=merge_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:23:15.177924+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T15:23:15.177924+00:00
[2023-03-29 15:55:39,135] {python.py:173} INFO - Done. Returned value was: None
[2023-03-29 15:55:39,156] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_merge_dag, task_id=merge_task, execution_date=20230329T152315, start_date=20230329T155538, end_date=20230329T155539
[2023-03-29 15:55:39,219] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-29 15:55:39,363] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
