[2023-03-29 15:39:04,597] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.start_task scheduled__2023-03-28T10:05:00+00:00 [queued]>
[2023-03-29 15:39:04,610] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.start_task scheduled__2023-03-28T10:05:00+00:00 [queued]>
[2023-03-29 15:39:04,610] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 15:39:04,611] {taskinstance.py:1357} INFO - Starting attempt 2 of 4
[2023-03-29 15:39:04,611] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 15:39:04,634] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): start_task> on 2023-03-28 10:05:00+00:00
[2023-03-29 15:39:04,642] {standard_task_runner.py:52} INFO - Started process 232 to run task
[2023-03-29 15:39:04,646] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_merge_dag', 'start_task', 'scheduled__2023-03-28T10:05:00+00:00', '--job-id', '502', '--raw', '--subdir', 'DAGS_FOLDER/data_merge.py', '--cfg-path', '/tmp/tmpc48mpcvr', '--error-file', '/tmp/tmp4xgb8857']
[2023-03-29 15:39:04,648] {standard_task_runner.py:80} INFO - Job 502: Subtask start_task
[2023-03-29 15:39:04,714] {task_command.py:369} INFO - Running <TaskInstance: data_merge_dag.start_task scheduled__2023-03-28T10:05:00+00:00 [running]> on host bc45bc710023
[2023-03-29 15:39:04,816] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kartaca
AIRFLOW_CTX_DAG_ID=data_merge_dag
AIRFLOW_CTX_TASK_ID=start_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T10:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-28T10:05:00+00:00
[2023-03-29 15:39:04,818] {logging_mixin.py:115} INFO - DAG has been started...
[2023-03-29 15:39:04,818] {python.py:173} INFO - Done. Returned value was: DAG has been started...
[2023-03-29 15:39:04,847] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_merge_dag, task_id=start_task, execution_date=20230328T100500, start_date=20230329T153904, end_date=20230329T153904
[2023-03-29 15:39:04,899] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-29 15:39:04,942] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
